apiVersion: v1
kind: Pod                                      #manifest for defaultmem.yml
metadata:
  name: constraints-mem-demo
spec:
  containers:
  - name: constraints-mem-demo-ctr
    image: nginx
    resources:
      limits:                                  #limits in defaultmem.yml=1000Mi
        memory: "1200Mi"                     
      requests:                                #requests in defaultmem.yml=500Mi
        memory: "300Mi"


