apiVersion: batch/v1
kind: CronJob
metadata:
 name: cron
spec:
 schedule: "* * * * *"
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - image: ubuntu
           name: sumant
           command: ["/bin/bash", "-c", "echo Hello, Sumant; sleep 5"]
         restartPolicy: Never
